# Copyright 2020-2025 Hewlett Packard Enterprise Development LP
# Copyright 2004-2019 Cray Inc.
# Other additional copyright holders may be indicated within.
#
# The entirety of this work is licensed under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
#
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
GPU_SRCS = gpu-nvidia.c gpu-nvidia-cub.cc gpu-nvidia-pgas.cc

SRCS = $(GPU_SRCS)

GPU_OBJS = $(addprefix $(GPU_OBJDIR)/,$(addsuffix .o,$(basename $(GPU_SRCS))))
GPU_OBJS += $(GPU_OBJDIR)/gpu-nvidia-pgas-dlink.o $(GPU_OBJDIR)/gpu-nvidia-cub-dlink.o

NVCC_RUNTIME_CXXFLAGS = -ccbin g++ -O3 -Xcompiler -fPIC --gpu-architecture=$(CHPL_MAKE_GPU_ARCH) -std=c++14
NVCC_RUNTIME_INCLS = $(filter -I% -D%,$(RUNTIME_INCLS))  # To avoid issues with using options like `-Wno-unused`

RUNTIME_CXXFLAGS_NOCUDA = $(RUNTIME_CXXFLAGS) -Wno-unused-variable -Wno-unused-function

# TODO: clang-14 wants offload-arch to be passed multiple times and doesn't accept
# a comma-separated list.
RUNTIME_CXXFLAGS += -x cuda -Wno-unknown-cuda-version \
                    -Xclang -fcuda-allow-variadic-functions \
                    --offload-arch=$(CHPL_MAKE_GPU_ARCH) \
                    --cuda-include-ptx=all

# With cuda 11, cub headers have unused typedefs
RUNTIME_CXXFLAGS += -Wno-error=unused-local-typedef


ifeq ($(shell test $(CHPL_MAKE_LLVM_VERSION) -ge 15; echo "$$?"),0)
	# With cuda 11, cub headers have deprecated builtins
	RUNTIME_CXXFLAGS += -Wno-error=deprecated-builtins \
			    -Wno-error=unknown-pragmas
endif

$(RUNTIME_OBJ_DIR)/gpu-nvidia-cub.o: gpu-nvidia-cub.cc \
                                         $(RUNTIME_OBJ_DIR_STAMP)
	$(CXX) -c $(CXX11_STD) $(RUNTIME_CXXFLAGS) $(RUNTIME_INCLS) -o $@ $<

# $(RUNTIME_OBJ_DIR)/gpu-nvidia-pgas.o: gpu-nvidia-pgas.cc \
# 										  $(RUNTIME_OBJ_DIR_STAMP)
# 	$(CXX) -c $(CXX11_STD) $(RUNTIME_CXXFLAGS) $(RUNTIME_INCLS) -o $@ $<

$(RUNTIME_OBJ_DIR)/gpu-nvidia-pgas.o: gpu-nvidia-pgas.cc \
                                         $(RUNTIME_OBJ_DIR_STAMP)
	nvcc -x cu $(NVCC_RUNTIME_CXXFLAGS) --device-c -Xcompiler -fPIC $(NVCC_RUNTIME_INCLS) -lnvshmem -o $@ $<

$(RUNTIME_OBJ_DIR)/gpu-nvidia-pgas-dlink.o: $(RUNTIME_OBJ_DIR)/gpu-nvidia-pgas.o \
                                                $(RUNTIME_OBJ_DIR_STAMP)
	nvcc $(NVCC_RUNTIME_CXXFLAGS) --device-link $(NVCC_RUNTIME_INCLS) -lnvshmem -o $@ $<

$(RUNTIME_OBJ_DIR)/gpu-nvidia-cub-dlink.o: $(RUNTIME_OBJ_DIR)/gpu-nvidia-cub.o \
												$(RUNTIME_OBJ_DIR_STAMP)
	nvcc $(NVCC_RUNTIME_CXXFLAGS) --device-link $(NVCC_RUNTIME_INCLS) -o $@ $<